# This job is to test different maven profiles in sdk branch again Pull Request raised
# This workflow targets Java with Maven execution

name: TestNG SDK Test workflow for Maven

on:
  pull_request:
    branches: [ "master", "sdk" ]
    types: [ opened, reopened ]

jobs:
  maven-run:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix:
        java: [ '8', '11', '17' ]
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
    name: TestNG Repo ${{ matrix.Java }} - ${{ matrix.os }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@fix/browserstack/issue-19'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME
      - name: 'BrowserStackLocal Setup'
        uses: 'browserstack/github-actions/setup-local@fix/browserstack/issue-19'
        with:
          local-testing: start
          local-identifier: random
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run mvn test
        run: |
          mvn compile
          mvn test
      - name: Run mvn profile sample-local-test
        run: |
          mvn compile
          mvn test -P sample-local-test
      - name: Run mvn profile sample-test
        run: |
          mvn compile
          mvn test -P sample-test